#!/usr/bin/env bash
#Install nginx on your web-01 server
apt-get update
apt-get -y install nginx

file="/var/www/html/index.html"
echo "Holberton School" > "$file"

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/ronald45251997 permanent;" /etc/nginx/sites-enabled/default

service nginx start
