#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to HAproxy
apt-get update
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*
echo "frontend load-banlancer
    bind *:80
    mode http
    default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
    balance roundrobin
    server 1848-web-01 35.237.149.87:80 check
    server 1848-web-02 35.227.68.31:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
